baseURL: "https://krupskyi.com/"
title: krupskyi
paginate: 5
theme: PaperMod

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Krupskyi
  description: "A litle blog about DevOps methodology, clouds and everything around"
  keywords: [DevOps, Cloud, AWS, Golang, Terraform, Kubernetes, k8s]
    #author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon16x16"
    favicon32x32: "favicon/favicon32x32"
    apple_touch_icon: "favicon/apple-touch-icon"
    safari_pinned_tab: "favicon/favicon.ico"

  label:
    text: "Krupskyi"
    icon: favicon/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Krupskyi
    subtitle: "Platfom Engineer"
    imageUrl: "favicon/apple-touch-icon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar
    buttons:
      - name: Posts
        url: posts
      # - name: CV
      #   url: cv
      - name: Projects
        url: projects
  socialIcons:
    - name: twitter
      url: "https://twitter.com/serhii_krupskyi"
    - name: github
      url: "https://github.com/SerhiiK"
    - name: RSS
      url: "index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    responsiveImages: true
    thumbnailInList: true

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about
      url: /about
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    #noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
